---
- name: Setup Webserver
  hosts: webserver
  become: true
  tasks:
  - name: Install httpd
    package:
      name: httpd
      state: present

  - name: Deploy web content
    copy:
      content: "{{ web_content }}"
      dest: /var/www/html/index.html

  - name: Restart httpd service
    service:
      name: httpd
      state: restarted