---
- name: ssh hardening
  hosts: webserver
  become: true
  tasks:
  - name: Ensure password authentication is disabled
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PasswordAuthentication'
      line: 'PasswordAuthentication no'

  - name: Restart sshd
    service:
      name: sshd
      state: restarted

  - name: set authorized key
    authorized_key:
      user: user
      state: present
      key: "{{ lookup('file', '~/.ssh/id_ecdsa.pub') }}"