---
- name: create motd from template
  hosts: webserver
  become: true

  tasks:

  - name: Query dog facts api
    uri:
      url: https://dog-facts-api.herokuapp.com/api/v1/resources/dogs/all
      return_content: true
    register: dog_facts

  - name: set motd from template
    template:
      src: templates/motd.j2
      dest: /etc/motd
      owner: root
      group: root
      mode: 0644
