---
- name: Test Rescue
  hosts: localhost
  tasks:
  - name: Handle the error
    block:
      - name: Print a message
        debug:
          msg: 'I execute normally'

      - name: Force a failure
        command: /bin/false

      - name: Print a message
        debug:
          msg: "I'm never executed"

    rescue:
      - name: Print when errors
        debug:
          msg: 'I caught an error, can do stuff here to fix it'