---
- name: Play with variables
  hosts: node1
  vars_files:
  - vars/my_vars.yml
  vars_prompt:
  - name: mykey
    prompt: "Enter access Key"
    private: false
      
  tasks:
  - name: print my variables
    debug:
      msg: "{{ my_num }}"
